# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push:
    branches: [ brian-dev,test ]
  pull_request:
    branches: [ brian-dev,test ]

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: everlytic/branch-merge@1.1.2
        with:
          target_branch: 'test'
          commit_message_template: '[Automated] Merged {source_ref} into target {target_branch}'

jobs:
  buildAndTest:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Test
        run: npm test
